In [1]:
import torch

In [2]:
x = 5

In [3]:
x = torch.tensor(5)

In [4]:
vector = torch.tensor([10, 20, 30])

In [9]:
matrix = torch.tensor([[1,2],
                       [3,4]])

In [10]:
tensor3d = torch.tensor([[[1,2], [3,4]], [[5,6], [7,8]]])

In [11]:
print(tensor3d)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
matrix.dtype

torch.int64

In [15]:
tensor3d.dtype

torch.int64

In [16]:
tensor3d.ndim

3

In [17]:
matrix.ndim

2

In [18]:
x.ndim

0

Basic Tensor Operation

In [19]:
a = [1, 2, 3]
b = [4, 5, 6]

In [20]:
a = torch.tensor(a)
b = torch.tensor(b)

In [21]:
a + b

tensor([5, 7, 9])

In [22]:
a * b

tensor([ 4, 10, 18])

In [23]:
m = torch.tensor([[1, 2, 3],
                  [4,5,6]])

In [24]:
m.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [25]:
m.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [26]:
m.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [27]:
zeros = torch.zeros(3,3)

In [28]:
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [29]:
ones = torch.ones(2, 4)

In [30]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
random = torch.rand(2,3)

In [32]:
random

tensor([[0.1194, 0.7237, 0.4611],
        [0.8063, 0.5818, 0.3735]])

In [33]:
x = torch.tensor([1, 2, 3, 4], dtype = torch.float)

In [34]:
x.sum()

tensor(10.)

In [36]:
x.mean()

tensor(2.5000)

In [37]:
x.std()

tensor(1.2910)

In [38]:
x.max()

tensor(4.)

In [40]:
x.min()

tensor(1.)

In [42]:
from torchvision import datasets, transforms # MNIST
from torch.utils.data import DataLoader

In [43]:
data = datasets.MNIST(root='./data', train=True, download=True, transform=transforms.ToTensor())

100%|██████████| 9.91M/9.91M [00:01<00:00, 6.07MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 161kB/s]
100%|██████████| 1.65M/1.65M [00:01<00:00, 1.52MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 7.18MB/s]


In [44]:
loader = torch.utils.data.DataLoader(data, batch_size=60000, shuffle=True)

In [45]:
images, _ = next(iter(loader))

In [46]:
images

tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        ...,


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0.

In [47]:
mean = images.mean()
std = images.std()

In [48]:
print(mean)
print(std)

tensor(0.1307)
tensor(0.3081)


In [49]:
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((mean,), (std))
])

In [50]:
train_data = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
test_data = datasets.MNIST(root='./data', train=False, download=True, transform=transform)

In [51]:
train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
test_loader = DataLoader(test_data, batch_size=32, shuffle=False)

NN

In [52]:
import torch.nn as nn
import torch.nn.functional as f

In [53]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(28 * 28, 128)
    self.fc2 = nn.Linear(128, 64)
    self.fc3 = nn.Linear(64, 10)

  def forward(self, x):
    x = x.view(-1, 28*28)
    x = f.relu(self.fc1(x))
    x = f.relu(self.fc2(x))
    x = self.fc3(x)
    return x


model = Net()

In [54]:
import torch.optim as optim

In [55]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [57]:
epochs = 10

for epoch in range(epochs):
    running_loss = 0.0
    for images, labels in train_loader:
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()

    print(f"Epoch {epoch+1} - Loss: {running_loss / len(train_loader):.4f}")

Epoch 1 - Loss: 0.5853
Epoch 2 - Loss: 0.2416
Epoch 3 - Loss: 0.1831
Epoch 4 - Loss: 0.1467
Epoch 5 - Loss: 0.1216
Epoch 6 - Loss: 0.1040
Epoch 7 - Loss: 0.0906
Epoch 8 - Loss: 0.0798
Epoch 9 - Loss: 0.0705
Epoch 10 - Loss: 0.0631


In [58]:
correct = 0
total = 0

with torch.no_grad():
  for images, labels in test_loader:
    outputs = model(images)
    _, predicted = torch.max(outputs.data, 1) # >> [0.1, 0.05, 0.3, "0.6", 0.0, 0.2, 0.1, 0.1, 0.3, 0.15]
    total += labels.size(0)
    correct += (predicted == labels).sum().item()

accuracy = 100 * correct / total
print(f'Accuracy: {accuracy:.2f}')


Accuracy: 97.32
