# **Install Numpy**

In [ ]:
!pip install numpy

NumPy is usually imported under the np alias.

In [ ]:
import numpy as np

# **Checking NumPy Version**

The **version string** is stored under **__version__ attribute**.

In [ ]:
np.__version__

'2.0.2'

# **NumPy Creating Arrays**

>NumPy is used to work with arrays.
>> The **array object** in NumPy is called **ndarray**.

>We can create a **NumPy ndarray** object by using the **array() function**.

In [ ]:
x = [1,2,3]
y = [4,5,6]

res = x + y
res

[1, 2, 3, 4, 5, 6]

In [ ]:
arr = np.array([12,20,30,40,50,60])

In [ ]:
print(arr)

[12 20 30 40 50 60]


In [ ]:
type(arr)

numpy.ndarray

**To create an ndarray**

>We can **pass** a **list**, **tuple** or any **array-like object** into the ```array()``` method, and it will be **converted into an ndarray**

In [ ]:
arr = np.array((10,20,30,40,50,60))

In [ ]:
arr

array([10, 20, 30, 40, 50, 60])

**Create an aray within specified range**

```np.arange()``` method can be used to replace ```np.array(range())``` method

In [ ]:
arr = np.arange(0, 21, 3)

In [ ]:
print(arr)
print(type(arr))

[ 0  3  6  9 12 15 18]
<class 'numpy.ndarray'>


**Create an array of evenly spaced numbers within specified range**

```np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False)``` has 5 parameters:
- ```start```: start number (inclusive)
- ```stop```: end number (inclusive unless ```endpoint``` set to ```False```)
- ```num_of_elements```: number of elements contained in the array
- ```endpoint```: boolean value representing whether the ```stop``` number is inclusive or not
- ```retstep```: boolean value representing whether to return the step size

In [ ]:
arr, step_size = np.linspace(0,10, 5,endpoint=False, retstep=True)

In [ ]:
print(arr)

[0. 2. 4. 6. 8.]


In [ ]:
print(arr.size)

17


**Create an array of random values of given shape**

```np.random.rand()``` method returns values in the range [0,1)

In [ ]:
arr = np.random.rand(3,4)
print(arr)

[[0.20071098 0.38442116 0.68047047 0.19503633]
 [0.20008912 0.09440452 0.36564311 0.48160244]
 [0.44008946 0.05649488 0.81847564 0.26543135]]


**Create an array of zeros of given shape**

- ```np.zeros()```: create array of all zeros in given shape
- ```np.zeros_like()```: create array of all zeros with the same shape and data type as the given input array

In [ ]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = [[1,2,3], [4,5,6]]
ones = np.zeros_like(arr)
print(ones)

[[0 0 0]
 [0 0 0]]


**Create an array of ones of given shape**

- ```np.ones()```: create array of all ones in given shape
- ```np.ones_like()```: create array of all ones with the same shape and data type as the given input array

In [ ]:
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
arr = [[1,2,3], [4,5,6]]
ones = np.ones_like(arr)
print(ones)

[[1 1 1]
 [1 1 1]]


**Create an empty array of given shape**

- ```np.empty()```: create array of empty values in given shape
- ```np.empty_like()```: create array of empty values with the same shape and data type as the given input array

Notice that the initial values are not necessarily set to zeroes.

They are just some garbage values in random memory addresses.

In [ ]:
empty = np.empty((2,2))
print(empty)
print(empty.dtype)

[[3.31962216e-315 0.00000000e+000]
 [5.49470885e-096 5.99073709e+140]]
float64


**Create an array of constant values of given shape**

- ```np.full()```: create array of constant values in given shape
- ```np.full_like()```: create array of constant values with the same shape and data type as the given input array

In [ ]:
full = np.full((4,4), 4)
print(full)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [ ]:
arr = np.array([[1,2], [3,4]], dtype=np.float64)
full = np.full_like(arr, 5)
print(full)

[[5. 5.]
 [5. 5.]]


**Create an identity matrix of given size**

- ```np.eye(size)```: create an identity matrix of given size
    - ```size```: the size of the identity matrix
- ```np.identity()```: same as ```np.eye()``` but does not carry parameters

In [ ]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**Create an array with given values on the diagonal**

In [ ]:
arr = np.random.rand(5,5)
print(arr)

[[0.62411029 0.80413866 0.24254926 0.87682865 0.97012432]
 [0.75734152 0.87405483 0.60074848 0.4255561  0.06517794]
 [0.24368606 0.27322506 0.53962396 0.30806304 0.85833336]
 [0.83956454 0.30966316 0.0397135  0.88248541 0.64162389]
 [0.54455263 0.07177938 0.23183757 0.63120223 0.35793335]]


Extract values on the diagonal

In [ ]:
print('Values on the diagonal: ' + str(np.diag(arr)))

Values on the diagonal: [0.62411029 0.87405483 0.53962396 0.88248541 0.35793335]


Not necessarily to be a square matrix

In [ ]:
arr = np.random.rand(5,3)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.83307107 0.73008282 0.57601957]
 [0.46997894 0.74687668 0.53483032]
 [0.85489517 0.72681809 0.07527104]
 [0.65113436 0.385261   0.20050177]
 [0.8599504  0.01462649 0.01696049]]
Values on the diagonal: [0.83307107 0.74687668 0.07527104]


Create a matrix given values on the diagonal

> All non-diagonal values set to zeros

In [ ]:
arr = np.diag([1,2,3,4,5,6])
print(arr)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


# **Dimensions in Arrays**

A **dimension** in arrays is **one level** of **array depth** (nested arrays).

**Nested array:** are arrays that **have arrays as their elements.**

## **0-D Arrays**

>**0-D arrays**, **,or Scalars**: are the **elements** in an array.
>>**Each value in an array is a 0-D array.**

In [ ]:
# create 0-D array with value '10'

arr=np.array('10')
print(arr)

10


## **1-D Arrays**

>An **array** that has **0-D arrays** as its **elements** is called **uni-dimensional** or **1-D array**.

>These are the **most common** and **basic** arrays.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## **2-D Arrays**

>An **array** that has **1-D arrays** as its **elements** is called a **2-D array**.

>These are often **used** to **represent matrix** or **2nd order tensors**.



**NumPy** has a whole **sub module** dedicated towards **matrix operations** called numpy.mat

In [ ]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr)

[[10 20 30]
 [40 50 60]]


## **3-D arrays**

>An **array** that has **2-D arrays** (**matrices**) as its **elements** is called **3-D array.**

>These are often used to **represent** a **3rd order tensor.**

In [ ]:
arr = np.array([[[10,20,30],[40,50,60]],[[10,20,30],[40,50,60]]])
print(arr)

[[[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 60]]]


## **Check Number of Dimensions?**

NumPy Arrays provides the **ndim** **attribute** that **returns** an **integer** that tells us how many **dimensions** the array have.

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(f"Number of dimensions in Array is :" ,a.ndim)
print(f"Number of dimensions in Array is :" ,b.ndim)
print(f"Number of dimensions in Array is :" ,c.ndim)
print(f"Number of dimensions in Array is :" ,d.ndim)

Number of dimensions in Array is : 0
Number of dimensions in Array is : 1
Number of dimensions in Array is : 2
Number of dimensions in Array is : 3


## **Higher Dimensional Arrays**

An **array** can have **any number of dimensions**.

>When the array is created, **you can define** the **number** of **dimensions** by using the **ndmin** argument.

In [ ]:
arr = np.array([10,20,30,40,50], ndmin=5)

print(arr)

print(f"Number of dimensions in Array is :", arr.ndim)

[[[[[10 20 30 40 50]]]]]
Number of dimensions in Array is : 5


#  **NumPy Array Indexing**

>Array indexing is the same as accessing an array element.

>You can access an array element by referring to its index number.

>The indexes in NumPy arrays **start with 0**, meaning that the **first element **has index **0**, and the **second** has index **1** etc.

In [ ]:
#Access first element

arr= np.array([10,20,30,40,50,60,70,80,90,100])

print(arr[0])

10


In [ ]:
#Access second element

arr= np.array([10,20,30,40,50,60,70,80,90,100])

print(arr[1])

20


In [ ]:
#Get third and fourth elements from the following array and add them.

arr= np.array([10,20,30,40,50,60,70,80,90,100])

print(arr[2]+arr[3])

70


## **Access 2-D Arrays**
To access elements from 2-D arrays we can use **comma separated integers** representing **the dimension** and the **index of the element.**

>**dimension index also starts from 0**

In [ ]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(f"First element from first Dimension {arr[0,0]}")

First element from first Dimension 10


In [ ]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(f"First element from second Dimension {arr[1,0]}")

First element from second Dimension 60


## **Access 3-D Arrays**
To access elements from 3-D arrays we can use **comma separated integers **representing the **dimensions** and the **index of the element.**

In [ ]:
arr = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,200,300]]])

print(arr)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 200 300]]]


In [ ]:
#Access the third element of the second array of the first array:
print(arr[0,1,2])

60


In [ ]:
arr = np.array([[[[ 1,  2], [ 3,  4]],
                 [[ 5,  6], [ 7,  8]]],

                [[[ 9, 10], [11, 12]],
                 [[13, 14], [15, 16]]]])
arr

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [ ]:
res1 = arr[0,1,1,1]
res2 = arr[1,0,1,1]
res3 = arr[1,1,0,1]

In [ ]:
res3

np.int64(14)

### **Explanation**
**The first number represents the first dimension, which contains two arrays:**

     [ [ 10,20,30 ] , [ 40,50,60] ]

**and:**

    [ [ 70,80,90 ] , [ 100,200,300 ] ]

**Since we selected 0, we are left with the first array:**

    [ [ 10,20,30 ] , [ 40,50,60] ]


**The second number represents the second dimension, which also contains two arrays:**


    [ 10,20,30 ]

**and:**

    [ 40,50,60]

**Since we selected 1, we are left with the second array:**

    [ 40,50,60]

**The third number represents the third dimension (element) , which contains three values:**

    40

    50

    60

**Since we selected 2, we end up with the third value:**

    60

## **Negative Indexing**

>Use negative indexing to access an array from the end.

In [ ]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(f"Last element from first Dimension {arr[0,-1]}")

Last element from first Dimension 50


# **NumPy Array Slicing**



**Slicing in python means taking elements from one given index to another given index.**

We pass slice instead of index like this:

    [start:end]

We can also define the step, like this:

    [start:end:step]

If we **don't** pass **start** its considered **0**

If we **don't** pass **end** its considered **length** of array **in that dimension**

If we **don't** pass **step** its considered **1**

In [ ]:
#Slice elements from index 1 to index 5 from the following array

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:1])

[2 3 4 5]


> **Note:** The result **includes** the **start** index, but **excludes** the **end** index.

In [ ]:
#Slice elements from index 4 to the end of the array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:6:1])

[5 6]


In [ ]:
#Slice elements from the beginning to index 4 (not included):

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4:1])

[1 2 3 4]


# **Negative Slicing**


**Use the minus operator to refer to an index from the end**

In [ ]:
#Slice from the index 3 from the end to index 1 from the end

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


# **Slicing 2-D Arrays**


In [ ]:
#From the second element, slice elements from index 1 to index 4 (not included)

arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(arr[1,1:4])

[70 80 90]


In [ ]:
#From both elements, return index 2:

arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(arr[0:2,2])

[30 80]


In [ ]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(arr[0:2,1:4])

[[20 30 40]
 [70 80 90]]


# **NumPy Array Shape**


The shape of an array is the number of elements in each dimension.

NumPy arrays have an **attribute** called **shape** that **returns** a **tuple** with **each index** having the **number** of **corresponding** **elements**.

In [ ]:
#Print the shape of a 2-D array

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)  #OUTPUT 2 >>> Two elements in first dimension , 4 >>> Four elements in second dimension

(2, 4)


In [ ]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

arr = np.array([1,2,3,4] , ndmin=5)


print('shape of array :', arr.shape)  #arr has 5 dimensions, in each dimension there is only one element except for the last dimension has 4 elements ([1, 2, 3, 4]).

shape of array : (1, 1, 1, 1, 4)


In [ ]:
arr

array([[[[[1, 2, 3, 4]]]]])

# **NumPy Array Reshaping**



> By reshaping we can **add** or **remove** **dimensions** or **change** **number** of elements in **each** **dimension**.

**Reshape From 1-D to 2-D**
the outermost dimension will have 2 arrays, each with 6 elements:

In [ ]:
#Convert the following 1-D array with 12 elements into a 2-D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 6)

print(newarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


## **Reshape From 1-D to 3-D**
The outermost dimension will have 2 arrays that contains 2 arrays, each with 3 elements:

In [ ]:
#Convert the following 1-D array with 12 elements into a 3-D array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2,2,3)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
newarr.shape

(2, 2, 3)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4))   #The example returns the original array, so it is a view

[[1 2 3 4]
 [5 6 7 8]]


# **Flattening the arrays**



**Flattening array means converting a multidimensional array into a 1D array.**

We can use **reshape(-1)** to do this.

In [ ]:
arr = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,200,300]]])
print(arr)


newarr = arr.reshape(-1)
print(newarr)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 200 300]]]
[ 10  20  30  40  50  60  70  80  90 100 200 300]
