# **Tensorflow V1**

In [1]:
import tensorflow as tf

## **Try**

Disable eager execution to use TensorFlow v1-style sessions

In [2]:
tf.compat.v1.disable_eager_execution()

Define a TensorFlow constant

In [3]:
x = tf.constant("Tensorflow")

Print the Tensor object (only its properties, not its value)

In [4]:
print(x)

Tensor("Const:0", shape=(), dtype=string)


Create a session in TensorFlow v1 compatibility mode

In [5]:
sess = tf.compat.v1.Session()

Run the session to evaluate the tensor 'x'

In [6]:
output = sess.run(x)

Print the actual value of 'x'

In [7]:
print(output)

b'Tensorflow'


Close the session properly

In [8]:
sess.close()

## **Add 2 numbers**

In [54]:
x = tf.constant(4)
y = tf.constant(10)

In [55]:
z = tf.add(x,y)

In [52]:
z

<tf.Tensor 'Add:0' shape=() dtype=int32>

In [11]:
print(z)

Tensor("Add:0", shape=(), dtype=int32)


In [56]:
sess = tf.compat.v1.Session()

In [57]:
output = sess.run(z)

In [58]:
output

np.int32(14)

In [59]:
print(output)

14


In [15]:
sess.close()

Open a session to run the computation

In [16]:
with tf.compat.v1.Session() as sess:
    output = sess.run(z)
    print(output)

14


## **Matrix Multiplication**

In [17]:
import numpy as np

In [18]:
# Create two 1D arrays (vectors) using numpy
var1 = np.arange(1, 13, dtype=np.int32)  # Creates an array [1, 2, ..., 12]
var2 = np.arange(15, 27, dtype=np.int32) # Creates an array [15, 16, ..., 26]

In [19]:
# Print arrays (Optional Debugging Step)
print(var1)  # Output: [1, 2, ..., 12]
print(var2)  # Output: [15, 16, ..., 26]

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[15 16 17 18 19 20 21 22 23 24 25 26]


In [20]:
# Reshape the numpy arrays into matrices
# var1 is reshaped into a 3x4 matrix
mat1 = tf.constant(var1, shape=[3, 4])

In [21]:
# var2 is reshaped into a 4x3 matrix
mat2 = tf.constant(var2, shape=[4, 3])

In [22]:
# Perform matrix multiplication (mat1 * mat2)
res = tf.matmul(mat1, mat2)

In [23]:
# Print the Tensor object (metadata, not actual value)
print(res)  # Output: <tf.Tensor 'MatMul:0' shape=(3,3) dtype=int32>

Tensor("MatMul:0", shape=(3, 3), dtype=int32)


In [24]:
# Open a session to execute the matrix multiplication
with tf.compat.v1.Session() as sess:
    # Compute the result
    output = sess.run(res)

    # Print the actual resulting matrix
    print(output)

# No need to manually close the session since 'with' statement manages it

[[210 220 230]
 [522 548 574]
 [834 876 918]]


## **Task**

add , sub , multi , divide

In [25]:
v1 = tf.constant([1,2,3,4])
v2 = tf.constant([6,7,8,9])

Res

In [26]:
a = tf.add(v1,v2)
s = tf.subtract(v1,v2)
m = tf.multiply(v1,v2)
d = tf.divide(v1,v2)

with tf.compat.v1.Session() as sess:
  print(sess.run(a))
  print(sess.run(s))
  print(sess.run(m))
  print(sess.run(d))

[ 7  9 11 13]
[-5 -5 -5 -5]
[ 6 14 24 36]
[0.16666667 0.28571429 0.375      0.44444444]


##  **Linear Regression using TF**

y = wx +b

In [27]:
# Generate random input data
x_data = np.random.randn(4, 9)  # Input features (4 samples, 9 features)
w_data = np.random.randn(9, 1)  # Weights (9 features, 1 output)
b_data = np.zeros(4)            # Bias (4 samples, 1 bias each)

In [28]:
# Define TensorFlow constants for computation
x = tf.constant(x_data, shape=[4, 9])  # Input matrix (4x9)
w = tf.constant(w_data, shape=[9, 1])  # Weight matrix (9x1)
b = tf.constant(b_data, shape=[4, 1])  # Bias vector (4x1)

In [29]:
# Linear regression formula: y = wx + b
y = tf.add(tf.matmul(x, w), b)  # Matrix multiplication (4x9) * (9x1) = (4x1), then add bias

In [30]:
# Print the Tensor object (metadata, not actual values)
print(y)  # Output: <tf.Tensor 'Add_2:0' shape=(4,1) dtype=float64>

Tensor("Add_2:0", shape=(4, 1), dtype=float64)


In [31]:
# Open a session to execute the computation
with tf.compat.v1.Session() as sess:
    # Compute and print the predicted values
    print(sess.run(y))

# No need to manually close the session since 'with' statement manages it

[[ 2.38901774]
 [ 5.43842906]
 [ 6.83545095]
 [-3.48450277]]


## **Variable**

In [60]:
var1 = tf.Variable(12, name="variable1")
var2 = tf.Variable(13, name="variable2")

In [62]:
# with tf.compat.v1.Session() as sess:
#   sess.run(var1)

initializer

In [34]:
init = tf.compat.v1.global_variables_initializer()

In [35]:
with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(var1))

12


## **Linear Regression using TF (Variable)**

**Task**

In [36]:
# [[1,2,3]] ---->> w
# [[3], [4], [4]] ---->> x
# 1 ------->> b

In [37]:
w = tf.Variable([[1,2,3]], shape=(1,3))
x = tf.constant([[3], [4], [4]], shape=(3,1))
b = tf.Variable(1)

In [38]:
res = tf.add(tf.matmul(w, x), b)

In [39]:
init = tf.compat.v1.global_variables_initializer()

In [40]:
with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(res))

[[24]]
