In [1]:
import tensorflow as tf

In [3]:
tf.compat.v1.disable_eager_execution()

In [25]:
x = tf.constant("Tensorflow")

In [26]:
x

<tf.Tensor 'Const_4:0' shape=() dtype=string>

In [27]:
sess = tf.compat.v1.Session()

In [28]:
output = sess.run(x)

In [29]:
output

b'Tensorflow'

In [30]:
sess.close()

In [31]:
x = tf.constant(4)
y = tf.constant(10)

In [33]:
z = tf.add(x, y)

In [34]:
z

<tf.Tensor 'Add_1:0' shape=() dtype=int32>

In [37]:
sess = tf.compat.v1.Session()

In [38]:
output = sess.run(z)

In [39]:
output

np.int32(14)

In [40]:
with tf.compat.v1.Session() as sess:
  output = sess.run(z)
  print(output)

14


In [41]:
import numpy as np

In [42]:
v1 = tf.constant([1, 2, 3, 4])
v2 = tf.constant([6, 7, 8, 9])

In [45]:
add_ = tf.add(v1, v2)
sub_ = tf.subtract(v1, v2)
multi_ = tf.multiply(v1, v2)
divide_ = tf.divide(v1, v2)

In [47]:
for x in [add_, sub_, multi_, divide_]:
  with tf.compat.v1.Session() as sess:
    output = sess.run(x)
    print(output)

[ 7  9 11 13]
[-5 -5 -5 -5]
[ 6 14 24 36]
[0.16666667 0.28571429 0.375      0.44444444]
